### PR TITLE
Issue 77 - circular reference naivete

### LINKED ISSUE #77: Broken circularDeepEqual
v3.0.2

```ts
const x = [1]
const left =  [{ a: [1], b:  x  }]
const right = [{ a:  x,  b: [1] }]

// should returns true, but returns false
circularDeepEqual( left, right )
```

[Sandbox](https://eval.js.hyoo.ru/#!code=const%20compare%20%3D%20%24mol_import.module%28%0A%09'https%3A%2F%2Fesm.sh%2Ffast-equals'%0A%29.circularDeepEqual%0A%0Aconst%20x%20%3D%20%5B1%5D%0Aconst%20left%20%3D%20%20%5B%7B%20a%3A%20%5B1%5D%2C%20b%3A%20%20x%20%20%7D%5D%0Aconst%20right%20%3D%20%5B%7B%20a%3A%20%20x%2C%20%20b%3A%20%5B1%5D%20%7D%5D%0A%0A%24mol_assert_equal%28%0A%09compare%28%20left%2C%20right%20%29%2C%0A%09true%2C%0A%29)

### PR DESCRIPTION
**Pull request by tquetano-netflix**
## Reason for change

Checking of already-compared circular objects was naive, creating false inequality comparisons. See #77 for more details.

## Change

Convert cache from `WeakSet` to `WeakMap` setup, and make the checks more targeted to the specific comparison. Inspiration was taken from [how `lodash` handles their circular reference checks](https://github.com/lodash/lodash/blob/master/.internal/equalObjects.js#L40).

Resolves #77

### CODE REVIEW

File: src/utils.ts [hunk 1]
```diff
@@ -109,24 +130,29 @@ export function createCircularEqualCreator(isEqual?: EqualityComparator) {
...
 
-      if (isCacheableA || isCacheableB) {
-        const hasA = isCacheableA && cache.has(a);
-        const hasB = isCacheableB && cache.has(b);
-
-        if (hasA || hasB) {
-          return hasA && hasB;
-        }
+      if (isCacheableA !== isCacheableB) {
+        return false;
```
Comment (tquetano-netflix) [inline src/utils.ts:134]: We can eagerly return if the types differ, since they cannot be equal.
